mode: inorder
poses:
  - pose:
     position:
        x: 1.0
        y: -2.0
        z: 0.0
     orientation:
        x: 0.0
        y: 0.0
        z: 0.70
        w: 0.70
  - pose:
     position:
        x: 2.0
        y: 3.0
        z: 0.0
     orientation:
        x: 0.0
        y: 0.0
        z: 0.70
        w: 0.70
  - pose:
     position:
        x: 6.0
        y: -4.0
        z: 0.0
     orientation:
        x: 0.0
        y: 0.0
        z: 0.70
        w: 0.70
  - pose:
     position:
        x: -6.5
        y: -2.0
        z: 0.0
     orientation:
        x: 0.0
        y: 0.0
        z: 0.70
        w: 0.70
  - pose:
     position:
        x: -6.5
        y: -2.0
        z: 0.0
     orientation:
        x: 0.0
        y: 0.0
        z: 0.25
        w: 0.25
